### ISSUE TITLE
Consider making this class static or a readonly record/struct

### ISSUE THREAD

**Issue by mrjavaguy** [barnesyard/TargetsGame#3]
https://github.com/barnesyard/TargetestGame/blob/2fbe6880c753d0a085037e58dec7eb79fcfbbb40/TargetsGameApp/Program.cs#L28

**Comment by barnesyard** [comment]
This is the kind of input I am looking for! Why should I consider making this change?

**Comment by mrjavaguy** [comment]
Use Static Classes when you need a container for global functions, utility methods, or values that do not depend on the state of an instance. Static classes are perfect for shared, state-independent functionalities.

Use Records when you need to represent data entities with immutability and require value-based equality comparisons. Records are an ideal choice for modeling immutable data, especially in scenarios where immutability, concise syntax, and comparison based on content matter.

Also, some of the comments I am doing is to encourage you to do some research :)

**Comment by barnesyard** [comment]
Thanks, I wanted to do more research, but it felt like there was so much information and I was wanting to make sure I was understanding your intentions.

**Comment by barnesyard** [comment]
I did some research. I don't think this class can be static. The Cell class has an instance of the Coordinate class and the Grid class has many instances of the Cell class. These instances are used in comparisons. If I had a static class I could not have multiple instances. 
So, `struct` vs `record`: Since the `Coordinate` class is not referencing any other classes (only has int members) and the data flows one way, I can choose to make it a `struct`. It would still need to be one way for a record but I would use a record if I had an instance of another class that I implemented.
